name: Mirsv
main: com.mirsv.Mirsv
version: 1.14.0
softdepend: [Vault]
author: Cokes_86, DayBreak, CatNote

commands:
  mirsv:
    description: Mirsv main command
  gmute:
    description: Global Mute Plugin
  clearchat:
    description: Clear Chat Plugin
  itemtag:
    description: ItemTag Plugin
  bc:
    description: BroadCast Plugin
  cl:
    description: CallPlayer Plugin
  wc:
    description: WhisperChat Plugin
  party:
    description: Party Plugin
  pc:
    description: Party Plugin
  playtime:
    description: PlayTime Plugin
  forbidden:
    description: ForbiddenWord Plugin
