name: Mirsv
main: com.mirsv.Mirsv
version: 1.12.12.1
softdepend: [Vault]
author: ___Moonshine___, CatNote

commands:
  mirsv:
    description: Mirsv main command
  gmute:
    description: Global Mute Plugin
  clearchat:
    description: Clear Chat Plugin
  itemtag:
    description: ItemTag Plugin
  warning:
    description: Warning Plugin
  prefix:
    description: Prefix Plugin
  bc:
    description: BroadCast Plugin
  cl:
    description: CallPlayer Plugin
  dm:
    description: ControlDeathMessage Plugin
  wc:
    description: WhisperChat Plugin
  party:
    description: Party Plugin
  pc:
    description: Party Plugin
  콜로세움:
    description: PvPTeleport Plugin
  천공섬:
    description: PvPTeleport Plugin
  캠핑장:
    description: PvPTeleport Plugin
  guide:
    description: Guide Plugin
  추천:
    description: Recommand
  부동산:
    description: EasyResidence Plugin
  머리:
    description: HeadChange Plugin
  playtime:
    description: PlayTime Plugin
  np:
    description: NoPickup Plugin