name: Mirsv
main: com.mirsv.Mirsv
version: 1.12.20.2
softdepend: [Vault]
author: ___Moonshine___, CatNote, _Marlang

commands:
  mirsv:
    description: Mirsv main command
  gmute:
    description: Global Mute Plugin
  clearchat:
    description: Clear Chat Plugin
  itemtag:
    description: ItemTag Plugin
  warning:
    description: Warning Plugin
  prefix:
    description: Prefix Plugin
  bc:
    description: BroadCast Plugin
  cl:
    description: CallPlayer Plugin
  dm:
    description: ControlDeathMessage Plugin
  wc:
    description: WhisperChat Plugin
  party:
    description: Party Plugin
  pc:
    description: Party Plugin
  콜로세움:
    description: PvPTeleport Plugin
  천공섬:
    description: PvPTeleport Plugin
  캠핑장:
    description: PvPTeleport Plugin
  guide:
    description: Guide Plugin
  추천:
    description: Recommand
  부동산:
    description: EasyResidence Plugin
  머리:
    description: HeadChange Plugin
  playtime:
    description: PlayTime Plugin
  np:
    description: NoPickup Plugin
  gamble:
    description: BingoGamble Plugin
  forbidden:
    description: ForbiddenWord Plugin
  안녕: 
    description: Say "Hi" to player
  오피: 
    description: Fake OP
  신원: 
    description: PlayerID Plugin
  야생: 
    description: Mine World Random TP
  채집: 
    description: Mine World Random TP
  네더: 
    description: Mine World Random TP
  지옥: 
    description: Mine World Random TP
  엔드: 
    description: Mine World Random TP
  엔더: 
    description: Mine World Random TP
  닉네임: 
    description: ChangeName Plugin