name: Mirsv
main: com.mirsv.Mirsv
version: 1.8
softdepend: [Vault]

commands:
  mirsv:
    description: Mirsv main command
  gmute:
    description: Global Mute Plugin
  clearchat:
    description: Clear Chat Plugin
  itemtag:
    description: ItemTag Plugin
  warning:
    description: Warning Plugin
  prefix:
    description: Prefix Plugin
  bc:
    description: BroadCast Plugin
  cl:
    description: CallPlayer Plugin
  dm:
    description: ControlDeathMessage Plugin
  wc:
    description: WhistleChat Plugin