name: Mirsv
main: com.mirsv.Mirsv
version: 1.14.0
author: Cokes_86, DayBreak, CatNote

commands:
  mirsv:
    description: Mirsv main command
  globalmute:
    description: 전체 유저를 뮤트할 때 사용됩니다.
    aliases: [gmute]
  clearchat:
    description: 채팅을 청소할 때 사용됩니다.
    aliases: [chatclear, cc]
  itemtag:
    description: ItemTag Plugin
  bc:
    description: BroadCast Plugin
  cl:
    description: CallPlayer Plugin
  wc:
    description: WhisperChat Plugin
  party:
    description: Party Plugin
  pc:
    description: Party Plugin
  forbidden:
    description: ForbiddenWord Plugin
