name: Mirsv
main: com.mirsv.Mirsv
version: ${project.version}
author: Cokes_86, DayBreak, CatNote

commands:
  mirsv:
    description: Mirsv main command
  globalmute:
    description: 전체 유저를 뮤트할 때 사용됩니다.
    aliases: [gmute]
  clearchat:
    description: 채팅을 청소할 때 사용됩니다.
    aliases: [chatclear, cc]
  itemtag:
    description: ItemTag Plugin
  cl:
    description: CallPlayer Plugin
  wc:
    description: WhisperChat Plugin
  party:
    description: Party Plugin
  pc:
    description: Party Plugin
  forbidden:
    description: ForbiddenWord Plugin
  g:
    description: AdvancedChat 기본 명령어
  tc:
    description: AdvancedChat 기본 명령어
  lc:
    description: AdvancedChat 기본 명령어
    aliases: [l]
  nc:
    description: AdvancedChat 기본 명령어
  mod:
    description: AdvancedChat 기본 명령어
    aliases: [m]
  admin:
    description: AdvancedChat 기본 명령어
    aliases: [a]
  bc:
    description: AdvancedChat 기본 명령어
  spychat:
    description: AdvancedChat 기본 명령어
  nickname:
    description: Nickname Plugin
  nick:
    description: Nickname Plugin
  prefix:
    description: CustomPrefix Plugin