name: Mirsv
main: com.mirsv.Mirsv
version: ${project.version}
author: Cokes_86, DayBreak, CatNote
softdepend: [Towny, LuckPerms, Vault, dynmap]

commands:
  mirsv:
    description: Mirsv main command
  globalmute:
    description: 전체 유저를 뮤트할 때 사용됩니다.
    aliases: [gmute]
  clearchat:
    description: 채팅을 청소할 때 사용됩니다.
    aliases: [chatclear]
  itemtag:
    description: ItemTag Plugin
  wc:
    description: WhisperChat Plugin
  party:
    description: Party Plugin
  pc:
    description: Party Plugin
  forbidden:
    description: ForbiddenWord Plugin
  g:
    description: AdvancedChat 기본 명령어
  tc:
    description: AdvancedChat 기본 명령어
  lc:
    description: AdvancedChat 기본 명령어
    aliases: [l]
  nc:
    description: AdvancedChat 기본 명령어
  mod:
    description: AdvancedChat 기본 명령어
    aliases: [m]
  admin:
    description: AdvancedChat 기본 명령어
    aliases: [a]
  bc:
    description: AdvancedChat 기본 명령어
  spychat:
    description: AdvancedChat 기본 명령어
  ac:
    description: AdvancedChat 기본 명령어
  nickname:
    description: Nickname Plugin
  nick:
    description: Nickname Plugin
  prefix:
    description: CustomPrefix Plugin
  과제:
    description: 과제 GUI 확인
  아침:
    description: 편의 플러그인
  저녁:
    description: 편의 플러그인
  사탕수수:
    description: 편의 플러그인
  조용히:
    description: 편의 플러그인
  경고:
    description: 경고
  경고관리:
    description: 경고 관리자
  cl:
    description: Call Player
  발렌타인:
    description: event command
  주식:
    description: Stock
  보관함:
    description: Delivery Service
  시세상점:
    description: Market Manager
  playtime:
    description: PlayTime